### ISSUE TITLE
Improve export for Tailwind

### ISSUE THREAD

**Issue by fmaclen** [fmaclen/chromabox#80]
We might need to add some hard-coded rules but essentially we want to try to replicate the setup of a typical Tailwind project.
If a particular color has 12 variants, then we use default to the `50, 100, 200 ... 900, 950` naming convention.

Separately, regardless of the number of variants on each color, the export will need to be split into 2 parts (CSS and JS config), where the colors are a defined as HSL variables in such a way to allow using alpha values like Tailwind's default colors, for example:

```css
:root {
	--chromeo-50: 0 0% 99%;
	--chromeo-100: 0 0% 97%;
	--chromeo-200: 0 0% 91%;
	--chromeo-300: 0 0% 81%;
	--chromeo-400: 0 0% 67%;
	--chromeo-500: 0 0% 50%;
	--chromeo-600: 0 0% 25%;
	--chromeo-700: 0 0% 24%;
	--chromeo-800: 0 0% 21%;
	--chromeo-900: 0 0% 16%;
	--chromeo-950: 0 0% 1%;
	--accent: 158 91% 25%;
}
```

```ts
export default {
	theme: {
		extend: {
			colors: {
				chromeo: {
					50: 'hsl(var(--chromeo-50) / <alpha-value>)',
					100: 'hsl(var(--chromeo-100) / <alpha-value>)',
					200: 'hsl(var(--chromeo-200) / <alpha-value>)',
					300: 'hsl(var(--chromeo-300) / <alpha-value>)',
					400: 'hsl(var(--chromeo-400) / <alpha-value>)',
					500: 'hsl(var(--chromeo-500) / <alpha-value>)',
					600: 'hsl(var(--chromeo-600) / <alpha-value>)',
					700: 'hsl(var(--chromeo-700) / <alpha-value>)',
					800: 'hsl(var(--chromeo-800) / <alpha-value>)',
					900: 'hsl(var(--chromeo-900) / <alpha-value>)',
					950: 'hsl(var(--chromeo-950) / <alpha-value>)'
				},
				accent: {
					DEFAULT: 'hsl(var(--accent) / <alpha-value>)'
				}
			}
		},
	},
	plugins: []
} satisfies Config;
```

If the user has chosen HEX as the default color format then we skip the `<alpha-value>`, but if the user chose RGB we can probably use the same technique to do:
```js
--chromeo-50: 255 255 255;

50: 'rgb(var(--chromeo-50) / <alpha-value>)'
```
